#!/usr/bin/env python3

import os
import django

os.environ.setdefault( 'DJANGO_SETTINGS_MODULE', 'architect.settings' )
django.setup()

import time
import random

from architect.TimeSeries.TimeSeries import getTS

complexes = {
              'cplx01-site1': {
                         'cost': 2,
                         'availability': 0.95 + ( ( random.random() - 0.5 ) * 0.05 ),
                         'reliability': 0.90 + ( ( random.random() - 0.5 ) * 0.05 )
                      },
              'cplx01-site2': {
                         'cost': 1,
                         'availability': 0.90 + ( ( random.random() - 0.5 ) * 0.01 ),
                         'reliability': 0.80 + ( ( random.random() - 0.5 ) * 0.01 )
                      },
              'cplx01-site3': {
                         'cost': 5,
                         'availability': 0.80 + ( ( random.random() - 0.5 ) * 0.02 ),
                         'reliability': 0.95 + ( ( random.random() - 0.5 ) * 0.02 )
                      },
              'cplx01-site4': {
                         'cost': 10,
                         'availability': 0.50 + ( ( random.random() - 0.5 ) * 0.04 ),
                         'reliability': 0.98 + ( ( random.random() - 0.5 ) * 0.04 )
                      },
              'cplx01-site5': {
                         'cost': 2,
                         'availability': 0.90 + ( ( random.random() - 0.5 ) * 0.01 ),
                         'reliability': 0.90 + ( ( random.random() - 0.5 ) * 0.01 )
                      },

            }


data = {
         'web_requests': 50,
         'count': 10
       }

ts = getTS()

timestamp = time.time()

ts_list = []

for name, details in complexes.items():
  ts_list.append( ( 'complex.{0}.cost'.format( name ), ( timestamp, details[ 'cost' ] ) ) )
  ts_list.append( ( 'complex.{0}.availability'.format( name ), ( timestamp, details[ 'availability' ] ) ) )
  ts_list.append( ( 'complex.{0}.reliability'.format( name ), ( timestamp, details[ 'reliability' ] ) ) )

for key, value in data.items():
  ts_list.append( ( 'data.{0}'.format( key ), ( timestamp, value ) ) )

ts.put( ts_list )

print( timestamp )
