Vagrant.configure(2) do |config|
  #config.vm.box = "ubuntu/xenial64"
  config.vm.box = "geerlingguy/ubuntu1604"
  config.vm.communicator = "ssh"
  config.vm.guest = "linux"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "512"
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.name = 'tekton-architect'
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081


  # "install" architect
  config.vm.synced_folder "../architect", "/usr/lib/python3/dist-packages/architect", create: true, :mount_options => ["ro"]
  config.vm.synced_folder "../local", "/usr/local/architect", create: true, :mount_options => ["ro"]
  config.vm.synced_folder "../www", "/var/www/architect", create: true, :mount_options => ["ro"]
  config.vm.provision "file", source: "../architect.conf", destination: "/tmp/architect.conf"
  config.vm.provision "shell", inline: <<-ARCHITECT_CONFIG
set -e
set -x

echo "graphite-carbon	graphite-carbon/postrm_remove_databases	boolean	false" | debconf-set-selections

apt-get update
apt-get install -y python3-django python3-dateutil sqlite3 graphite-web graphite-carbon graphite-api apache2 libapache2-mod-wsgi-py3

python /usr/lib/python2.7/dist-packages/graphite/manage.py migrate
nohup python /usr/lib/python2.7/dist-packages/graphite/manage.py runserver 0.0.0.0:8081 0<&- &> /var/log/graphite-web.log &

mv /tmp/architect.conf /etc/apache2/sites-available/architect.conf
sed s/:80/:8080/ -i /etc/apache2/sites-available/architect.conf
echo "Listen 8080" >> /etc/apache2/ports.conf

a2ensite architect.conf

service apache2 reload

/usr/local/architect/util/manage.py migrate
/usr/local/architect/util/scanProject --apply /usr/lib/python3/dist-packages/architect/Plan/tests/project1/ /usr/lib/python3/dist-packages/architect/Plan/tests/includes/
/usr/local/architect/util/scanProject --apply /usr/lib/python3/dist-packages/architect/Plan/tests/project1/ /usr/lib/python3/dist-packages/architect/Plan/tests/includes/
/usr/local/architect/util/scanProject --apply /usr/lib/python3/dist-packages/architect/Plan/tests/project1/ /usr/lib/python3/dist-packages/architect/Plan/tests/includes/

ARCHITECT_CONFIG

end

