#!/usr/bin/env python3

import os
import django

os.environ.setdefault( 'DJANGO_SETTINGS_MODULE', 'architect.settings' )
django.setup()

import time
from architect.TimeSeries.libts import getTS

complexes = {
              'nuc1': {
                         'cost': 10,
                         'availability': 0.70,
                         'reliability': 0.999
                      },
              'nuc2': {
                         'cost': 12,
                         'availability': 0.80,
                         'reliability': 0.95
                      },
              'xps15': {
                         'cost': 20,
                         'availability': 0.50,
                         'reliability': 0.80
                      },

              'cplx8': {
                         'cost': 5,
                         'availability': 0.90,
                         'reliability': 0.92
                      },
            }


data = {
         'web_requests': 50,
       }

ts = getTS()

timestamp = time.time()

ts_list = []

for name, details in complexes.items():
  ts_list.append( ( 'complex.{0}.cost'.format( name ), ( timestamp, details[ 'cost' ] ) ) )
  ts_list.append( ( 'complex.{0}.availability'.format( name ), ( timestamp, details[ 'availability' ] ) ) )
  ts_list.append( ( 'complex.{0}.reliability'.format( name ), ( timestamp, details[ 'reliability' ] ) ) )

for key, value in data.items():
  ts_list.append( ( 'data.{0}'.format( key ), ( timestamp, value ) ) )

ts.put( ts_list )

print( timestamp )
