#!/usr/bin/env python3

import os
import django

os.environ.setdefault( 'DJANGO_SETTINGS_MODULE', 'architect.settings' )
django.setup()

from architect.Plan.models import Plan
from architect.Builder.models import Action, Job

ORDER_OF_OPERATIONS = [ 'move', 'build', 'destroy', 'rebuild' ]

print( 'Checking Plans...' )
for plan in Plan.objects.all():
  print( 'Checking plan "{0}"...'.format( plan ) )

  actions_needed = plan.max_inflight - Action.objects.filter( instance__plan=plan ).exclude( state={} ).count()

  if actions_needed <= 0:
    continue

  action_list = list( Action.objects.filter( instance__plan=plan, state={} ) )
  action_list.sort( key=lambda action: ORDER_OF_OPERATIONS.index( action.action ) )

  for action in action_list[ :actions_needed ]:
    action.start()

print( 'Running Jobs...' )
for job in Job.objects.filter( state__in=( 'new', 'done' ) ):
  print( 'Running job"{0}"...'.format( job ) )
  job.run()

print( 'Running Actions...' )
for action in Action.objects.exclude( state={} ):
  print( 'Running action "{0}"...'.format( action ) )
  action.run()

print( 'Done.' )
