#!/usr/bin/env python3

import os
import django

os.environ.setdefault( 'DJANGO_SETTINGS_MODULE', 'architect.settings' )
django.setup()

import logging

from architect.Plan.models import Plan
from architect.Builder.models import Action, Job

logging.basicConfig( level=logging.DEBUG )

print( 'Checking Plans...' )
for plan in Plan.objects.all():
  print( 'Checking plan "{0}"...'.format( plan ) )

  actions_needed = plan.max_inflight - Action.objects.filter( instance__plan=plan ).exclude( state={} ).count()

  if actions_needed <= 0:
    continue

  for action in Action.objects.filter( instance__plan=plan, state={} )[ :actions_needed ]:
    action.start()

print( 'Running Jobs...' )
for job in Job.objects.filter( state__in=( 'new', 'done' ) ):
  print( 'Running job"{0}"...'.format( job ) )
  job.run()

print( 'Running Actions...' )
for action in Action.objects.exclude( state={} ):
  print( 'Running action "{0}"...'.format( action ) )
  action.run()

print( 'Done.' )
