#!/usr/bin/env python3

import os
import django

os.environ.setdefault( 'DJANGO_SETTINGS_MODULE', 'architect.settings' )
django.setup()

from architect.Contractor.models import Complex, BluePrint
from architect.Contractor.libcontractor import getContractor

contractor = getContractor()

print( 'Getting master Complex lists...' )

master_list = set( list( contractor.getComplexes() ) )
local_list = set( Complex.objects.filter( contractor_id__isnull=False ).values_list( 'contractor_id', flat=True ) )

remove_list = list( local_list - master_list )
add_list = list( master_list - local_list )

for contractor_id in add_list:
  print( 'Adding "{0}"...'.format( contractor_id ) )
  details = contractor.getComplex( contractor_id )
  complex = Complex( contractor_id=contractor_id, site_id=details[ 'site' ] )
  complex.full_clean()
  complex.save()

for contractor_id in remove_list:
  complex = Complex.objects.get( contractor_id=contractor_id )
  if complex.tsname is None:   # not attached to  anything can just remove
    print( 'Deleting "{0}"...'.format( contractor_id ) )
    complex.delete()

  else:
    print( 'Disabeling "{0}"...'.format( contractor_id ) )
    complex.contractor_id = None
    complex.full_clean()
    complex.save()


print( 'Getting master BluePrint lists...' )

master_list = set( list( contractor.getBluePrints() ) )
local_list = set( BluePrint.objects.filter( contractor_id__isnull=False ).values_list( 'contractor_id', flat=True ) )

remove_list = list( local_list - master_list )
add_list = list( master_list - local_list )

for contractor_id in add_list:
  print( 'Adding "{0}"...'.format( contractor_id ) )
  blueprint = BluePrint( contractor_id=contractor_id )
  blueprint.full_clean()
  blueprint.save()

for contractor_id in remove_list:
  blueprint = BluePrint.objects.get( contractor_id=contractor_id )
  if blueprint.tsname is None:   # not attached to  anything can just remove
    print( 'Deleting "{0}"...'.format( contractor_id ) )
    blueprint.delete()

  else:
    print( 'Disabeling "{0}"...'.format( contractor_id ) )
    blueprint.contractor_id = None
    blueprint.full_clean()
    blueprint.save()

print( 'Done' )
